version: "3.1"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:${TAG:-latest}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - CONNECTION_MODE=http-keep-alive
    secrets:
      - dfp_users_vfarcic
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        reservations:
          memory: 10M
        limits:
          memory: 20M

  docs:
    image: vfarcic/docker-flow-proxy-docs:${TAG:-latest}
    networks:
      - proxy
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.serviceDomain=proxy.dockerflow.com,dockerflow.com
        - com.df.servicePath=/
      replicas: 2
      resources:
        reservations:
          memory: 5M
        limits:
          memory: 10M

networks:
  proxy:
    external: true

secrets:
  dfp_users_vfarcic:
    external: true
